const {chromium}=require('C:/Users/q9560/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{ const browser=await chromium.launch({headless:true,channel:"msedge"}); const page=await browser.newPage({viewport:{width:1366,height:768}}); const errors=[];page.on('pageerror',e=>errors.push(e.message)); await page.goto('http://127.0.0.1:1423/t63-smoke.html'); await page.getByRole('button',{name:'查看力量体系',exact:true}).waitFor();
await page.screenshot({path:'.zcode-tmp/t63/home.png'});
await page.getByRole('button',{name:'关闭入口',exact:true}).click(); await page.reload(); if(await page.getByRole('button',{name:'查看力量体系',exact:true}).count()) throw new Error('隐藏入口重载后仍存在');
await page.getByText('首页可选入口',{exact:true}).click(); await page.getByRole('checkbox',{name:'显示力量体系入口'}).check(); await page.getByRole('button',{name:'查看力量体系',exact:true}).click(); await page.getByRole('button',{name:'旧力量词条',exact:true}).waitFor(); await page.getByRole('button',{name:'新建力量体系（带可删提示）',exact:true}).click(); await page.getByRole('textbox',{name:'词条',exact:true}).fill('新体系'); await page.locator('.cm-content').waitFor();const body=await page.locator('.cm-content').innerText(); for(const word of ['等级边界','力量来源','成长条件','代价限制','主角例外','剧情展示','下一阶段期待']) if(!body.includes(word))throw new Error('提示缺失 '+word);
await page.screenshot({path:'.zcode-tmp/t63/guided.png'}); await page.locator('.cm-content').fill('我自由改写的力量设定。'); await page.getByRole('button',{name:'保存',exact:true}).click(); await page.getByRole('button',{name:'新体系',exact:true}).click();if(!(await page.locator('.cm-content').innerText()).includes('我自由改写的力量设定。'))throw new Error('重开正文丢失');await page.getByRole('button',{name:'取消',exact:true}).click();
await page.getByRole('button',{name:'从空白正文开始',exact:true}).click(); if((await page.locator('.cm-content').innerText()).trim()) throw new Error('空白被强加模板');await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByRole('button',{name:'全部词条',exact:true}).click();await page.getByRole('button',{name:'旧力量词条',exact:true}).waitFor(); await page.getByRole('button',{name:'刷新',exact:true}).click(); if(await page.getByRole('button',{name:'从空白正文开始',exact:true}).count()) throw new Error('全部筛选刷新后恢复力量体系'); await page.getByRole('button',{name:'力量体系',exact:true}).click(); await page.getByRole('button',{name:'世界观 1',exact:true}).click(); if(await page.getByRole('button',{name:'从空白正文开始',exact:true}).count())throw new Error('侧栏未复原全部筛选');
await page.setViewportSize({width:1024,height:768}); if(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth))throw new Error('横向溢出');await page.screenshot({path:'.zcode-tmp/t63/narrow.png'}); console.log(JSON.stringify({result:'首页开关重载、力量体系导航、七项提示、自由改写保存重开、空白正文、旧词条和 1024px 布局通过',errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});


